# Site settings
asset_version: 6
title: Turtl
email: andrew@turtl.it
description: The safe way to remember everything. Take all your important data with you.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://turtl.it"
permalink: "/:categories/:title/"

turtl_version: "0.6.3"
ext_version: "0.5.1"

# Build settings
markdown: kramdown
kramdown:
    parse_block_html: true
    auto_ids: true
    toc_levels: 1..3

exclude: 
  - Makefile
  - package.json
  - node_modules/
  - "*.less"

